/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bengkel;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Eighteenags
 */
public class Bantuan extends javax.swing.JFrame {

    /**
     * Creates new form Bantuan
     */
    public Bantuan() {
        initComponents();
        jMenuItem2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        pnlList = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblHeadQuest = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("4F-APP");
        Header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel3.setText("Sistem Transaksi Bengkel");
        Header.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 150, -1));

        jButton8.setBackground(new java.awt.Color(0, 204, 255));
        jButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Logout");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        Header.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 20, 100, -1));

        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 60));

        pnlList.setBackground(new java.awt.Color(0, 102, 255));
        pnlList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(pnlList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1370, 4));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblHeadQuest.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHeadQuest.setText("Jawaban dari pertanyaan anda :");

        lbl1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl1.setForeground(new java.awt.Color(0, 51, 204));
        lbl1.setText("1.  Bagaimana cara mengakses Aplikasi 4F-APP ini  >> Klik disini ");
        lbl1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl1MouseClicked(evt);
            }
        });

        lbl2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl2.setForeground(new java.awt.Color(0, 51, 204));
        lbl2.setText("2.  Kenapa saya tidak bisa login >> Klik disini");
        lbl2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl2MouseClicked(evt);
            }
        });

        lbl3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl3.setForeground(new java.awt.Color(0, 51, 204));
        lbl3.setText("3.  Bagaimana membuka koneksi database di 4F-APP >> Klik disini");
        lbl3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl3MouseClicked(evt);
            }
        });

        lbl4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl4.setForeground(new java.awt.Color(0, 51, 204));
        lbl4.setText("4.  Bagaimana apabila saya lupa Username atau Password >> Klik disini");
        lbl4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl4MouseClicked(evt);
            }
        });

        lbl5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl5.setForeground(new java.awt.Color(0, 51, 204));
        lbl5.setText("5.  Bagaimana saya keluar dari aplikasi 4F-APP ini >> Klik disini");
        lbl5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl5MouseClicked(evt);
            }
        });

        lbl6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl6.setForeground(new java.awt.Color(0, 51, 204));
        lbl6.setText("6.  Bagaimana cara menambahkan Data Baru pada 4F-APP ini >> Klik disini");
        lbl6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl6MouseClicked(evt);
            }
        });

        lbl7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl7.setForeground(new java.awt.Color(0, 51, 204));
        lbl7.setText("7.  Bagaimana cara mencetak Struk Penjualan >> Klik disini");
        lbl7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl7MouseClicked(evt);
            }
        });

        lbl8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl8.setForeground(new java.awt.Color(0, 51, 204));
        lbl8.setText("8.  Bagaimana saya bisa melihat Data Penjualan >> Klik disini");
        lbl8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl8MouseClicked(evt);
            }
        });

        lbl9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl9.setForeground(new java.awt.Color(0, 51, 204));
        lbl9.setText("9.  Bagaimana cara Mengubah Atau Mengahapus Data pada 4F-APP ini >> Klik disini");
        lbl9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl9MouseClicked(evt);
            }
        });

        lbl10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl10.setForeground(new java.awt.Color(0, 51, 204));
        lbl10.setText("10. Saya menemukan aplikasi ini sedikit ada eror , hubungi kami >> Klik disini");
        lbl10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeadQuest)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl1)
                            .addComponent(lbl2)
                            .addComponent(lbl3)
                            .addComponent(lbl4)
                            .addComponent(lbl5)
                            .addComponent(lbl6)
                            .addComponent(lbl7)
                            .addComponent(lbl8)
                            .addComponent(lbl9)
                            .addComponent(lbl10))))
                .addContainerGap(773, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeadQuest, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lbl1)
                .addGap(15, 15, 15)
                .addComponent(lbl2)
                .addGap(15, 15, 15)
                .addComponent(lbl3)
                .addGap(15, 15, 15)
                .addComponent(lbl4)
                .addGap(15, 15, 15)
                .addComponent(lbl5)
                .addGap(15, 15, 15)
                .addComponent(lbl6)
                .addGap(15, 15, 15)
                .addComponent(lbl7)
                .addGap(15, 15, 15)
                .addComponent(lbl8)
                .addGap(15, 15, 15)
                .addComponent(lbl9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl10)
                .addContainerGap(348, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1370, 690));

        jMenu1.setText("File");

        jMenuItem4.setText("Open DB-XAMPP");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem3.setText("Logout");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Bantuan");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Bantuan.png"))); // NOI18N
        jMenuItem1.setText("Tentang");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Help.png"))); // NOI18N
        jMenuItem2.setText("Bantuan");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(this.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        new FormLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void lbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl1MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Cara mengakses 4F-APP ini dengan langkah-langkah sbb :\n"
            + "\n1. Pastikan koneksi database Xampp telah berjalan , klik menu Open DB-Xampp jika belum"
            + "\n2. Setelah koneksi telah berjalan , Pilih hak akses Petugas/Pemilik , lalu isi username dan password"
            + "\n3. Setelah itu Klik tombol LOGIN", " Bantuan - Cara Akses 4F-APP", 1);
    }//GEN-LAST:event_lbl1MouseClicked

    private void lbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl2MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Kenapa login gagal :\n"
            + "\n1. Pastikan koneksi database Xampp telah berjalan , klik menu OpenDB-Xampp jika belum"
            + "\n2. Isi Username dan Password dengan benar"
            + "\n3. Perhatikan Username anda milik hak akses Pegawai atau Pemilik", " Bantuan - Login gagal", 1);
    }//GEN-LAST:event_lbl2MouseClicked

    private void lbl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl3MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Cara membuka koneksi Database Xampp :\n"
            + "\n1. Klik menu File Kemudian Open DB-Xampp , tunggu beberapa detik hingga muncul Xampp"
            + "\n2. Setelah itu klik Start Apache dan MySql"
            + "\n3. Setelah start selesai , Silahkan Minimize lalu Login-lah agar dapat menggunakan 4F-APP", " Bantuan - Cara Buka XAMPP", 1);
    }//GEN-LAST:event_lbl3MouseClicked

    private void lbl4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl4MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Saya lupa Username dan Password :\n"
            + "\n1. Klik lupa password apabila anda lupa Username atau Password"
            + "\n2. Akan ada pertanyaan pemulihan , Jawablah dengan benar semua"
            + "\n3. Apabila berhasil menjawab maka Username atau Password akan ditampilkan"
            + "\n4. Jika gagal anda bukan pemilik akun tersebut , Hubungi kami bila terjadi kesalahan", " Bantuan - Lupa Password", 1);
    }//GEN-LAST:event_lbl4MouseClicked

    private void lbl5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl5MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Cara Keluar Aplikasi ini :\n"
            + "\n1. Apabila anda ingin keluar , Klik Tanda X di pojok kanan atas"
            + "\n2. Apabila anda ingin Logout , Klik menu pilihan -> pilih Logout", " Bantuan - Keluar Atau Logout", 1);
    }//GEN-LAST:event_lbl5MouseClicked

    private void lbl6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl6MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Cara Menambahkan Data Baru :\n"
            + "\n1. Login ke Dalam 4F-APP"
            + "\n2. Pergi ke Menu Data , Pilih Data Yang Ingin Ditambahkan"
            + "\n3. Isi Form Sesuai Petunjuk "
            + "\n4. Klik Insert Apabila Selesai Mengisi Form", " Bantuan - Menambahkan Data", 1);
    }//GEN-LAST:event_lbl6MouseClicked

    private void lbl7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl7MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Cara Mencetak Struk Penjualan :\n"
            + "\n1. Pastikan Anda Telah Mengisi Form Pada Saat Penjualan"
            + "\n2. Setelah Itu Anda Bayar dan Anda Beralih Ke Halaman Selanjutnya"
            + "\n3. Di Halaman Tsb Pilih Cetak Struk", " Bantuan - Cetak Struk Penjualan", 1);
    }//GEN-LAST:event_lbl7MouseClicked

    private void lbl8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl8MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Cara Melihat Data Penjualan :\n"
            + "\n1. Untuk Melihat Data Laporan Dikhususkan Untuk Pemilik"
            + "\n2. Setelah Login Pergi ke Menu Laporan , Pilih -> (Laporan yang Anda Ingikan)"
            + "\n\nNB. Untuk Laporan Fitur Anda Harus Mengisi Form Tanggal Awal dan Tanggal Akhir", " Bantuan - Melihat Data Penjualan", 1);
    }//GEN-LAST:event_lbl8MouseClicked

    private void lbl9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl9MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Cara Mengubah Atau Menghapus Data :\n"
            + "\n1. Masuk Ke Menu Data"
            + "\n2. Klik Data Barang, Jasa Atau Pegawai, Lalu Anda Akan Beralih Ke Halaman Lain"
            + "\n3. Pilih Data Yang Berada Ditabel "
            + "\n4. Ubah Data Yang Ada Di Form Kemudian Klik Update"
            + "\n5. Untuk Menghapus data setelah poin 3 klik Delete.  ", " Bantuan - Mengubah Dan Menghapus Data", 1);
    }//GEN-LAST:event_lbl9MouseClicked

    private void lbl10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl10MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "BUG / EROR Aplikasi :\n"
            + "\nApabila Anda Menemukan Bug/Eror , Silahkan Hubungi CP Dibawah Ini :"
            + "\nContact : +628988860191 "
            + "\nE-Mail  : jalusancoko13@gmail.com", " Bantuan - Bug /  Eror Aplikasi", 1);
    }//GEN-LAST:event_lbl10MouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().open(new File("C:\\xampp\\xampp-control.exe"));
        } catch (IOException ex) {
            Logger.getLogger(FormLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "4F APP Adalah Aplikasi Sistem Informasi Transaksi 4F Motor"
                + "\nDibuat oleh Mahasiswa Kerja Praktek Teknik Informatika ITATS Surabaya dengan tujuan untuk"
                + "\nmembantu dan memudahkan 4F Motor dalam kegiatan Transaksi Dan Laporan."
                + "\n\nApplication Version 1.0.0", "Tentang 4F APP", 1);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new FormLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bantuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bantuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bantuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bantuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bantuan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lblHeadQuest;
    private javax.swing.JPanel pnlList;
    // End of variables declaration//GEN-END:variables
}
