/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bengkel;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FormLogin extends javax.swing.JFrame {

    Koneksi db = new Koneksi();
    Statement st;
    ResultSet rs;

    public static String userid_info;
    public static String UserWelcome;
    public static String password_info;

    /**
     * Creates new form homeLogin
     */
    public FormLogin() {
        initComponents();
        String lblCreate = "<html><u>Lupa Password ? Klik Disini</u></hmtl>";
        lblCreateAcc.setText(lblCreate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlBackground = new javax.swing.JPanel();
        pnlLogin = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblCreateAcc = new javax.swing.JLabel();
        lblPictUser = new javax.swing.JLabel();
        lblPictPass = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        cbShowPassword = new javax.swing.JCheckBox();
        cmBagian = new javax.swing.JComboBox<>();
        pnlTips = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTips = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnItemKeluar = new javax.swing.JMenuItem();
        mnBantuan = new javax.swing.JMenu();
        mnItemAbout = new javax.swing.JMenuItem();
        mnItemHelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("4F-APP");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackground.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlBackground.setAlignmentX(1.0F);
        pnlBackground.setAlignmentY(1.0F);
        pnlBackground.setMinimumSize(new java.awt.Dimension(1366, 768));
        pnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLogin.setBackground(new java.awt.Color(255, 255, 255));
        pnlLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(224, 224, 224), new java.awt.Color(234, 234, 234)));
        pnlLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/4F.PNG"))); // NOI18N
        pnlLogin.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 210, 130));

        btnLogin.setBackground(new java.awt.Color(51, 102, 255));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 380, 35));

        lblCreateAcc.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblCreateAcc.setForeground(new java.awt.Color(51, 51, 255));
        lblCreateAcc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCreateAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreateAccMouseClicked(evt);
            }
        });
        pnlLogin.add(lblCreateAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 170, 20));

        lblPictUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user.png"))); // NOI18N
        pnlLogin.add(lblPictUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 30, 30));

        lblPictPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/password.png"))); // NOI18N
        pnlLogin.add(lblPictPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 30, 30));

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsername.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtUsername.setOpaque(false);
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsernameKeyTyped(evt);
            }
        });
        pnlLogin.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 380, 33));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPassword.setToolTipText("Password");
        txtPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPassword.setOpaque(false);
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });
        pnlLogin.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 380, 30));

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUsername.setText("USERNAME");
        pnlLogin.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPassword.setText("PASSWORD");
        pnlLogin.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        lblUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUser.setText("Login Sebagai");
        pnlLogin.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        cbShowPassword.setBackground(new java.awt.Color(255, 255, 255));
        cbShowPassword.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cbShowPassword.setText("Tampilkan Password");
        cbShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowPasswordActionPerformed(evt);
            }
        });
        pnlLogin.add(cbShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, 20));

        cmBagian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmBagian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pegawai", "Pemilik" }));
        cmBagian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlLogin.add(cmBagian, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 160, 30));

        pnlBackground.add(pnlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 460, 480));

        pnlTips.setBackground(new java.awt.Color(245, 245, 245));
        pnlTips.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("barang, penjualan dan laporan 4F-APP");
        pnlTips.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Pastikan koneksi Database terhubung Klik \"Open Db-XAMPP\" Lalu Silahkan Klik pada \"Login\" untuk dapat mengakses Menu ");
        pnlTips.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        pnlBackground.add(pnlTips, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 860, 110));

        lblTips.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTips.setForeground(new java.awt.Color(102, 102, 102));
        lblTips.setText("Tips");
        pnlBackground.add(lblTips, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 40, 40));

        getContentPane().add(pnlBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 750));

        MenuBar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        mnFile.setText("File");

        jMenuItem1.setText("OPEN DB XAMPP");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnFile.add(jMenuItem1);

        mnItemKeluar.setText("Keluar");
        mnItemKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemKeluarActionPerformed(evt);
            }
        });
        mnFile.add(mnItemKeluar);

        MenuBar.add(mnFile);

        mnBantuan.setText("Bantuan");

        mnItemAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Bantuan.png"))); // NOI18N
        mnItemAbout.setText("Tentang");
        mnItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemAboutActionPerformed(evt);
            }
        });
        mnBantuan.add(mnItemAbout);

        mnItemHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Help.png"))); // NOI18N
        mnItemHelp.setText("Bantuan");
        mnItemHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemHelpActionPerformed(evt);
            }
        });
        mnBantuan.add(mnItemHelp);

        MenuBar.add(mnBantuan);

        setJMenuBar(MenuBar);

        setSize(new java.awt.Dimension(1385, 809));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        if (cmBagian.getSelectedItem().equals("Pegawai")){
            db.Connect();
            try{
                st = db.getConnection().createStatement();
                String sql = "SELECT * FROM pegawai WHERE username = '"+txtUsername.getText()+"' and password = '"+txtPassword.getText()+"'";
                    rs = st.executeQuery(sql);
                    if(rs.next()){
                        FormMenu mn = new FormMenu(rs.getString("id_pegawai"));
                        mn.setVisible(true);
                        this.dispose();
                    }
                    else{
                        JOptionPane.showMessageDialog(rootPane, "Gagal Login", "Pesan", JOptionPane.ERROR_MESSAGE);
                    }
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Koneksi Database Terputus !");
            }
        }else if (cmBagian.getSelectedItem().equals("Pemilik")){
            db.Connect();
            try{
                st = db.getConnection().createStatement();
                String sql = "SELECT * FROM pemilik WHERE username = '"+txtUsername.getText()+"' and password = '"+txtPassword.getText()+"'";
                    rs = st.executeQuery(sql);
                    if(rs.next()){
                        FormMenu mn = new FormMenu(rs.getString("id_pemilik"));
                        mn.setVisible(true);
                        this.dispose();
                    }
                    else{
                        JOptionPane.showMessageDialog(rootPane, "Gagal Login", "Pesan", JOptionPane.ERROR_MESSAGE);
                    }
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Koneksi Database Terputus !");
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Gagal Login", "Pesan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameKeyTyped

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordKeyTyped

    private void cbShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowPasswordActionPerformed
        // TODO add your handling code here:
        if (cbShowPassword.isSelected()) {
            txtPassword.setEchoChar((char) 0);

        } else {
            txtPassword.setEchoChar('•');

        }
    }//GEN-LAST:event_cbShowPasswordActionPerformed

    private void lblCreateAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateAccMouseClicked
        // TODO add your handling code here:
        if (cmBagian.getSelectedItem().equals("Pegawai")) {
            lupaPassword mnu = new lupaPassword();
            mnu.pnlLupaPassword.setVisible(true);
            mnu.pnlJawaban.setVisible(false);
            mnu.pnlLupaPasswordOwner.setVisible(false);
            mnu.pnlJawabanOwner.setVisible(false);
            mnu.setVisible(true);
            dispose();
        } else if (cmBagian.getSelectedItem().equals("Pemilik")) {
            lupaPassword mn = new lupaPassword();
            mn.pnlLupaPasswordOwner.setVisible(true);
            mn.pnlLupaPassword.setVisible(false);
            mn.pnlJawaban.setVisible(false);
            mn.pnlJawabanOwner.setVisible(false);
            mn.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_lblCreateAccMouseClicked

    private void mnItemKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnItemKeluarActionPerformed

    private void mnItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemAboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "4F APP Adalah Aplikasi Sistem Informasi Transaksi 4F Motor"
                + "\nDibuat oleh Mahasiswa Kerja Praktek Teknik Informatika ITATS Surabaya dengan tujuan untuk"
                + "\nmembantu dan memudahkan 4F Motor dalam kegiatan Transaksi Dan Laporan."
                + "\n\nApplication Version 1.0.0", "Tentang 4F APP", 1);
    }//GEN-LAST:event_mnItemAboutActionPerformed

    private void mnItemHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemHelpActionPerformed
        // TODO add your handling code here:
        new Bantuan().setVisible(true);
        dispose();
    }//GEN-LAST:event_mnItemHelpActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().open(new File("C:\\xampp\\xampp-control.exe"));

        } catch (IOException ex) {
            Logger.getLogger(FormLogin.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(this.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JButton btnLogin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbShowPassword;
    protected javax.swing.JComboBox<String> cmBagian;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblCreateAcc;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPictPass;
    private javax.swing.JLabel lblPictUser;
    private javax.swing.JLabel lblTips;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JMenu mnBantuan;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenuItem mnItemAbout;
    private javax.swing.JMenuItem mnItemHelp;
    private javax.swing.JMenuItem mnItemKeluar;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlTips;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
