/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bengkel;

import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Eighteenags
 */
public class FormPenjualan extends javax.swing.JFrame {

    String tgl,jam;
    Connection cn;
    ResultSet rs;
    Statement st;
    Koneksi db = new Koneksi();
    DefaultTableModel MdtBarang, MdtJasa, MdtTrans; 
    int cekstock;
    /**
     * Creates new form FormTransaksi
     */
    public FormPenjualan(String Id) {
        initComponents();
        jMenuItem5.setEnabled(false);
        id_pegawai.setText(Id);
        Jam();
        akses();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        pnlList = new javax.swing.JPanel();
        PanelTransaksi = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        text_id_transaksi = new javax.swing.JTextField();
        text_tanggal = new javax.swing.JTextField();
        text_jumlah = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        text_nama = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        text_harga = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbJasa = new javax.swing.JTable();
        textCariJasa = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBarang = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        textCariBarang = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        id_pegawai = new javax.swing.JTextField();
        text_id_jasa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        text_id_barang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        text_tunai = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        text_total = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbTransaksi = new javax.swing.JTable();
        PanelBayar = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        lblKembalian = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        LabJam = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnData = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnTransaksi = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        mnBantuan = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("4F-APP");
        Header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel3.setText("Sistem Transaksi Bengkel");
        Header.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 150, -1));

        jButton8.setBackground(new java.awt.Color(0, 204, 255));
        jButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Kembali>>");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        Header.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 20, -1, -1));

        pnlList.setBackground(new java.awt.Color(0, 102, 255));
        pnlList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelTransaksi.setBackground(new java.awt.Color(255, 255, 255));
        PanelTransaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Data Transaksi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 204, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("ID Transaksi");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tanggal");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        text_id_transaksi.setEditable(false);
        text_id_transaksi.setBackground(new java.awt.Color(255, 255, 255));
        text_id_transaksi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(text_id_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 190, -1));

        text_tanggal.setEditable(false);
        text_tanggal.setBackground(new java.awt.Color(255, 255, 255));
        text_tanggal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(text_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 190, -1));

        text_jumlah.setEditable(false);
        text_jumlah.setBackground(new java.awt.Color(255, 255, 255));
        text_jumlah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        text_jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_jumlahKeyTyped(evt);
            }
        });
        jPanel1.add(text_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 190, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Harga");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Nama Barang / Jasa");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        text_nama.setEditable(false);
        text_nama.setBackground(new java.awt.Color(255, 255, 255));
        text_nama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(text_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 190, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Jumlah Pembelian");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 20));

        text_harga.setEditable(false);
        text_harga.setBackground(new java.awt.Color(255, 255, 255));
        text_harga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(text_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 190, -1));

        jButton4.setBackground(new java.awt.Color(0, 153, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Tambah");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 200, 40));

        btnRefresh.setBackground(new java.awt.Color(0, 153, 255));
        btnRefresh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Reset");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 120, 40));

        PanelTransaksi.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 350, 260));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Jasa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 204, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbJasa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbJasa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbJasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbJasaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbJasaMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(tbJasa);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 60, 460, 190));

        textCariJasa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(textCariJasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 150, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Cari");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 80, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Cari Nama");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 70, 20));

        PanelTransaksi.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 480, 260));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Barang", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 204, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbBarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbBarang.setOpaque(false);
        tbBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbBarang);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 460, 190));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama_Barang", "Kategori" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 30, 130, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 80, -1));

        textCariBarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(textCariBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 150, -1));

        PanelTransaksi.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 260));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id_pegawai.setEditable(false);
        id_pegawai.setBackground(new java.awt.Color(255, 255, 255));
        id_pegawai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(id_pegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, -1));

        text_id_jasa.setEditable(false);
        text_id_jasa.setBackground(new java.awt.Color(255, 255, 255));
        text_id_jasa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(text_id_jasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 80, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("ID Jasa");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("ID Pegawai");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("ID Barang");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        text_id_barang.setEditable(false);
        text_id_barang.setBackground(new java.awt.Color(255, 255, 255));
        text_id_barang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(text_id_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Total Biaya");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, 30));

        jButton5.setBackground(new java.awt.Color(255, 0, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Batal Order");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 460, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Tunai");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, 20));

        text_tunai.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        text_tunai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_tunaiKeyTyped(evt);
            }
        });
        jPanel4.add(text_tunai, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 150, -1));

        jButton7.setBackground(new java.awt.Color(0, 204, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Bayar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 460, 50));

        text_total.setEditable(false);
        text_total.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel4.add(text_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 150, 40));

        PanelTransaksi.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 480, 260));

        jScrollPane3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tbTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTransaksiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbTransaksi);

        PanelTransaksi.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 840, 250));

        PanelBayar.setBackground(new java.awt.Color(255, 255, 255));
        PanelBayar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(0, 255, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Selesai");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        PanelBayar.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, 240, 60));

        jButton6.setBackground(new java.awt.Color(0, 0, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Cetak Struk");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        PanelBayar.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 240, 60));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kembali", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 204, 255))); // NOI18N
        jPanel6.setForeground(new java.awt.Color(0, 204, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblKembalian.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblKembalian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKembalian.setText("0");
        jPanel6.add(lblKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 40, 280, -1));

        PanelBayar.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 490, 110));

        jPanel5.setBackground(new java.awt.Color(0, 204, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Form Penjualan");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        LabJam.setBackground(new java.awt.Color(255, 255, 255));
        LabJam.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        LabJam.setForeground(new java.awt.Color(255, 255, 255));
        LabJam.setText("00:00:00");
        jPanel5.add(LabJam, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, 170, 30));

        mnFile.setText("File");

        jMenuItem1.setText("Open DB-XAMPP");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnFile.add(jMenuItem1);

        jMenuItem2.setText("Menu Utama");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnFile.add(jMenuItem2);

        jMenuBar2.add(mnFile);

        mnData.setText("Data");

        jMenuItem3.setText("Data Barang");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnData.add(jMenuItem3);

        jMenuItem4.setText("Data Jasa");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mnData.add(jMenuItem4);

        jMenuBar2.add(mnData);

        mnTransaksi.setText("Transaksi");

        jMenuItem5.setText("Penjualan");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mnTransaksi.add(jMenuItem5);

        jMenuBar2.add(mnTransaksi);

        mnBantuan.setText("Bantuan");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Bantuan.png"))); // NOI18N
        jMenuItem6.setText("Tentang");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        mnBantuan.add(jMenuItem6);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Help.png"))); // NOI18N
        jMenuItem7.setText("Bantuan");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        mnBantuan.add(jMenuItem7);

        jMenuBar2.add(mnBantuan);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlList, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(PanelBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 1360, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(PanelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlList, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().open(new File("C:\\xampp\\xampp-control.exe"));
        } catch (IOException ex) {
            Logger.getLogger(FormLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CariJasa();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tbBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBarangMouseClicked
        // TODO add your handling code here:
        int i = tbBarang.getSelectedRow();
        text_id_barang.setText((String) tbBarang.getValueAt(i, 0));
        text_nama.setText((String) tbBarang.getValueAt(i, 1));
        text_harga.setText((String) tbBarang.getValueAt(i, 2));
        cekstock = Integer.parseInt((String) tbBarang.getValueAt(i, 3));
        text_jumlah.setText("");
        text_jumlah.setEditable(true);
        text_id_jasa.setText("");
    }//GEN-LAST:event_tbBarangMouseClicked

    private void tbJasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbJasaMouseClicked
        // TODO add your handling code here:
        int i = tbJasa.getSelectedRow();
        text_id_jasa.setText((String) tbJasa.getValueAt(i, 0));
        text_nama.setText((String) tbJasa.getValueAt(i, 1));
        text_harga.setText((String) tbJasa.getValueAt(i, 2));
        text_jumlah.setText("1");
        text_jumlah.setEditable(false);
        text_id_barang.setText("");
    }//GEN-LAST:event_tbJasaMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        in_detail();
        LihatTabel();
        LihatTransaksi();
        text_nama.setText("");
        text_harga.setText("");
        text_jumlah.setText("");
        text_id_barang.setText("");
        text_id_jasa.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tbJasaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbJasaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tbJasaMouseEntered

    private void text_jumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_jumlahKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') && text_jumlah.getText().length() < 10
        || (c == KeyEvent.VK_BACK_SPACE)
        || (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();
}
    }//GEN-LAST:event_text_jumlahKeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        CancelTrans();
        LihatTabel();
        LihatTransaksi();
        text_nama.setText("");
        text_harga.setText("");
        text_jumlah.setText("");
        text_id_barang.setText("");
        text_id_jasa.setText("");
        jButton5.setEnabled(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       akses();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CariBarang();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(this.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "4F APP Adalah Aplikasi Sistem Informasi Transaksi 4F Motor"
                + "\nDibuat oleh Mahasiswa Kerja Praktek Teknik Informatika ITATS Surabaya dengan tujuan untuk"
                + "\nmembantu dan memudahkan 4F Motor dalam kegiatan Transaksi Dan Laporan."
                + "\n\nApplication Version 1.0.0", "Tentang 4F APP", 1);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void tbTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTransaksiMouseClicked
        // TODO add your handling code here:
        jButton5.setEnabled(true);
    }//GEN-LAST:event_tbTransaksiMouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new FormBarang(id_pegawai.getText()).setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        new Bantuan().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new FormMenu(id_pegawai.getText()).setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new FormJasa(id_pegawai.getText()).setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        db.Connect();
            String NamaFile = "/Laporan/Struk.jasper";
            HashMap hash = new HashMap();
        try {
            hash.put("id_penjualan", text_id_transaksi.getText());
            hash.put("tunai",text_tunai.getText());
            hash.put("kembali", lblKembalian.getText());
            CetakStruk(NamaFile,hash);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void text_tunaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_tunaiKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') && text_tunai.getText().length() < 10
        || (c == KeyEvent.VK_BACK_SPACE)
        || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_text_tunaiKeyTyped

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(text_total.getText().isEmpty()||text_tunai.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Total Atau Tunai Kosong !","Pesan",JOptionPane.ERROR_MESSAGE);
        }else{
            int tunai = Integer.parseInt(text_tunai.getText());
            int total = Integer.parseInt(text_total.getText());
            if(tunai >= total){
                int kembalian = tunai - total;
                lblKembalian.setText(""+kembalian);
                PanelBayar.setVisible(true);
                PanelTransaksi.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Nilai Tunai Kurang","Pesan",JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        new FormMenu(id_pegawai.getText()).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JLabel LabJam;
    private javax.swing.JPanel PanelBayar;
    private javax.swing.JPanel PanelTransaksi;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JTextField id_pegawai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblKembalian;
    private javax.swing.JMenu mnBantuan;
    private javax.swing.JMenu mnData;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenu mnTransaksi;
    private javax.swing.JPanel pnlList;
    private javax.swing.JTable tbBarang;
    private javax.swing.JTable tbJasa;
    private javax.swing.JTable tbTransaksi;
    private javax.swing.JTextField textCariBarang;
    private javax.swing.JTextField textCariJasa;
    private javax.swing.JTextField text_harga;
    private javax.swing.JTextField text_id_barang;
    private javax.swing.JTextField text_id_jasa;
    private javax.swing.JTextField text_id_transaksi;
    private javax.swing.JTextField text_jumlah;
    private javax.swing.JTextField text_nama;
    private javax.swing.JTextField text_tanggal;
    private javax.swing.JTextField text_total;
    private javax.swing.JTextField text_tunai;
    // End of variables declaration//GEN-END:variables

    private void CetakStruk(String sourcefilename, HashMap hash){
        cn = db.getConnection();
        try {
            InputStream report;
            report = getClass().getResourceAsStream(sourcefilename);
            JasperPrint jprint = JasperFillManager.fillReport(report,hash, cn);
            JasperViewer viewer = new JasperViewer(jprint, false);
            viewer.setFitPageZoomRatio();
            viewer.setVisible(true);
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
    }
    private void reset(){
        LihatTabel();
        LihatTransaksi();
        jButton5.setEnabled(false);
        text_nama.setText("");
        text_harga.setText("");
        text_jumlah.setText("");
        text_id_barang.setText("");
        text_id_jasa.setText("");
        textCariBarang.setText("");
        textCariJasa.setText("");
    }
    private void akses(){
        PanelBayar.setVisible(false);
        PanelTransaksi.setVisible(true);
        autoid_transaksi();
        Jam();
        LihatTabel();
        LihatTransaksi();
        jButton5.setEnabled(false);
        text_total.setText("");
        text_tunai.setText("");
        text_nama.setText("");
        text_harga.setText("");
        text_jumlah.setText("");
        text_id_barang.setText("");
        text_id_jasa.setText("");
        textCariBarang.setText("");
        textCariJasa.setText("");
    }
    
    private void Jam(){
        new Timer(0, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                Date skrg= new Date();
                SimpleDateFormat format= new SimpleDateFormat("HH:mm:ss");
                LabJam.setText(format.format(skrg));
                jam = format.format(skrg);
            }
            
        }).start();
        Date skrg= new Date();
        SimpleDateFormat format= new SimpleDateFormat("dd MMMM yyyy");
        SimpleDateFormat format2= new SimpleDateFormat("yyyy-MM-dd");
        tgl = format2.format(skrg);
        text_tanggal.setText(format.format(skrg));
    }
    
    private void autoid_transaksi(){
        db.Connect();
        try{
            String sql = "select max(right(id_penjualan,10)) as no from penjualan";
            st = db.getConnection().createStatement();
            rs = st.executeQuery(sql);
            while(rs.next()){
                if(rs.first() == false){
                    text_id_transaksi.setText("PJ0000000001");
                }
                else{
                    rs.last();
                    int set_id = rs.getInt(1)+1;
                    String no = String.valueOf(set_id);
                    int id_next = no.length();
                    for (int n = 0; n < 10 - id_next; n++) {
                        no = "0" + no;
                    }
                    text_id_transaksi.setText("PJ"+no);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void LihatTabel(){
        MdtBarang = new DefaultTableModel(){
        public boolean isCellEditable(int rowIndex, int mColIndex) {
            return false;
          }
        };
        MdtBarang.addColumn("Id");
        MdtBarang.addColumn("Nama");
        MdtBarang.addColumn("Harga");
        MdtBarang.addColumn("Stok");
        MdtBarang.addColumn("Kategori");
        tbBarang.setModel(MdtBarang);
        
        MdtJasa = new DefaultTableModel(){
        public boolean isCellEditable(int rowIndex, int mColIndex) {
            return false;
          }
        };
        MdtJasa.addColumn("Id");
        MdtJasa.addColumn("Nama");
        MdtJasa.addColumn("Harga");
        tbJasa.setModel(MdtJasa);
        db.Connect();
        try{
            MdtBarang.setRowCount(0);
            String sql = "SELECT * FROM barang";
            st = db.getConnection().createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                MdtBarang.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5)
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormPenjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try{
            String sql = "SELECT * FROM jasa";
            st = db.getConnection().createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                MdtJasa.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3)
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormPenjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void LihatTransaksi(){
        MdtTrans = new DefaultTableModel(){
            public boolean isCellEditable(int rowIndex, int mColIndex) {
                return false;
            }
        };
        MdtTrans.addColumn("Id Detail");
        MdtTrans.addColumn("Id Penjualan");
        MdtTrans.addColumn("Id Barang");
        MdtTrans.addColumn("Id Jasa");
        MdtTrans.addColumn("Nama");
        MdtTrans.addColumn("Harga");
        MdtTrans.addColumn("Jumlah");
        MdtTrans.addColumn("Total");
        tbTransaksi.setModel(MdtTrans);
        try{
            String sql = "SELECT id_detail, id_penjualan, id_barang, id_jasa, nama, harga, jumlah, total_biaya FROM detail_penjualan where id_penjualan = '"+text_id_transaksi.getText()+"'";
            st = db.getConnection().createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                MdtTrans.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7),
                    rs.getString(8)
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormPenjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void in_transaksi(){
        db.Connect();
        try{
            String sql1 = "select * from penjualan where id_penjualan = '"+text_id_transaksi.getText()+"'";
            st = db.getConnection().createStatement();
            rs = st.executeQuery(sql1);
            if(!rs.next()){
                String sql = "insert into penjualan values ('"+text_id_transaksi.getText()+"','"+id_pegawai.getText()+"','"+tgl+"','"+jam+"')";
                try{
                    st = db.getConnection().createStatement();
                    st.executeUpdate(sql);
                } catch (SQLException ex) {
                    Logger.getLogger(FormPenjualan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormPenjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void in_detail(){
        db.Connect();
        if(text_jumlah.getText().equals("") || text_jumlah.getText().equals("0")){
            JOptionPane.showMessageDialog(rootPane, "Inputan Kurang atau jumlah Nol !","Pesan",JOptionPane.ERROR_MESSAGE);
        }else{
            int harga = Integer.parseInt(text_harga.getText());
            int jumlah = Integer.parseInt(text_jumlah.getText());
            int total =  harga*jumlah ;
            int total2;
            if(text_total.getText().equals("")){
                total2=0;
            }
            else{
                total2 = Integer.valueOf(text_total.getText());
            }
            try{
                String sql;
                if(text_id_barang.getText().equals("")){
                    text_total.setText(String.valueOf(total2+total));
                    in_transaksi();
                    sql = "insert into detail_penjualan (id_penjualan, id_jasa, nama, harga, jumlah, total_biaya) values ('"+text_id_transaksi.getText()+"','"+text_id_jasa.getText()+"','"+text_nama.getText()+"','"+text_harga.getText()+"','"+text_jumlah.getText()+"','"+total+"')";
                    st = db.getConnection().createStatement();
                    st.executeUpdate(sql);
                }
                else if(text_id_jasa.getText().equals("")){
                    if(cekstock-Integer.parseInt(text_jumlah.getText())>=0){
                        text_total.setText(String.valueOf(total2+total));
                        in_transaksi();
                        sql = "insert into detail_penjualan (id_penjualan, id_barang, nama, harga, jumlah, total_biaya) values ('"+text_id_transaksi.getText()+"','"+text_id_barang.getText()+"','"+text_nama.getText()+"','"+text_harga.getText()+"','"+text_jumlah.getText()+"','"+total+"')";
                        st = db.getConnection().createStatement();
                        st.executeUpdate(sql);
                        int stockbaru = cekstock-Integer.parseInt(text_jumlah.getText());
                        String sql1 = "update barang set stock = "+stockbaru+" where id_barang = '"+text_id_barang.getText()+"'";
                        st = db.getConnection().createStatement();
                        st.executeUpdate(sql1);
                    }
                    else{
                        JOptionPane.showMessageDialog(rootPane, "Stock Kurang !", "Pesan", JOptionPane.ERROR_MESSAGE);
                    }
                } 
            } catch (SQLException ex) {
                Logger.getLogger(FormPenjualan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    private void CancelTrans(){
        db.Connect();
        int jawab = JOptionPane.showOptionDialog(null, "Yakin Membatalkan Transaksi ?", "Batal Transaksi",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, null, null, null);
        if(jawab == JOptionPane.YES_OPTION){
            int row = tbTransaksi.getSelectedRow();
            try {
                if(!("".equals(tbTransaksi.getModel().getValueAt(row, 2)))){
                    String idBarang = (String) tbTransaksi.getModel().getValueAt(row, 2);
                    String sql2 = "select stock from barang where id_barang = '"+idBarang+"'";
                    st = db.getConnection().createStatement();
                    rs = st.executeQuery(sql2);
                    if(rs.next()){
                        int stockbarucancel = Integer.parseInt(rs.getString(1));
                        int stockcancel = Integer.parseInt((String) tbTransaksi.getModel().getValueAt(row, 6));
                        stockbarucancel = stockbarucancel + stockcancel;
                        String sql1 = "update barang set stock = "+stockbarucancel+" where id_barang = '"+idBarang+"'";
                        st = db.getConnection().createStatement();
                        st.executeUpdate(sql1);
                    }
                }  
                st = db.getConnection().createStatement();
                int totalcancel = Integer.parseInt((String) tbTransaksi.getModel().getValueAt(row, 7));
                int total = Integer.parseInt(text_total.getText());
                text_total.setText(String.valueOf(total-totalcancel));
                String sql = "delete from detail_penjualan WHERE id_detail = '"+tbTransaksi.getModel().getValueAt(row, 0)+"'";
                st.getConnection().createStatement();
                st.executeUpdate(sql); 
            } catch (SQLException ex) {
                Logger.getLogger(FormPenjualan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }
    
    private void CariBarang(){
        db.Connect();
        if(textCariBarang.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Isikan Data yang akan di cari");
        }
        else{
            try{
                String pilihan = jComboBox1.getSelectedItem().toString();
                String sql = "select "+pilihan+" from barang where "+pilihan+" like '%"+textCariBarang.getText()+"%'";
                st = db.getConnection().createStatement();
                rs = st.executeQuery(sql);
                if(rs.next()){
                    MdtBarang.setRowCount(0);
                    sql = "select * from barang where "+pilihan+" like '%"+textCariBarang.getText()+"%'";
                    st = db.getConnection().createStatement();
                    rs = st.executeQuery(sql);
                    while(rs.next()){
                        MdtBarang.addRow(new Object[]{
                        rs.getString(1),
                        rs.getString(2),
                        rs.getString(3),
                        rs.getString(4),
                        rs.getString(5)
                        });
                    }
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Data Tidak Ada", "Pesan", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(FormPenjualan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    private void CariJasa(){
        db.Connect();
        if(textCariJasa.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Isikan Data yang akan di cari");
        }
        else{
            try{
                String sql = "select nama_jasa from jasa where nama_jasa like '%"+textCariJasa.getText()+"%'";
                st = db.getConnection().createStatement();
                rs = st.executeQuery(sql);
                if(rs.next()){
                    MdtJasa.setRowCount(0);
                    sql = "select * from jasa where nama_jasa like '%"+textCariJasa.getText()+"%'";
                    st = db.getConnection().createStatement();
                    rs = st.executeQuery(sql);
                    while(rs.next()){
                        MdtJasa.addRow(new Object[]{
                        rs.getString(1),
                        rs.getString(2),
                        rs.getString(3)
                        });
                    }
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Data Tidak Ada", "Pesan", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(FormPenjualan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
