/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bengkel;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author User
 */
public class FormMenu extends javax.swing.JFrame {
    /**
     * Creates new form FormMenu
     */
    String id_pegawai;
    Connection cn;
    ResultSet rs;
    Statement st;
    Koneksi db = new Koneksi();
    public FormMenu(String Id) {
        initComponents();
        id_pegawai = Id;
        lblHoverTransaksi.setVisible(false);
        lblHoverLaporan.setVisible(false);
        lblHoverAkun.setVisible(false);
        pnlTransaksi.setVisible(false);
        pnlMenuLaporan.setVisible(false);
        pnlMenuInfoAkun.setVisible(false);
        cekuser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        pnlList = new javax.swing.JPanel();
        pnlMenuLaporan = new javax.swing.JPanel();
        pnlHeaderLaporan = new javax.swing.JPanel();
        lblHdrHalLaporan = new javax.swing.JLabel();
        pnlLaporan = new javax.swing.JPanel();
        btnLaporanCus = new javax.swing.JButton();
        lblKetLaporanCus1 = new javax.swing.JLabel();
        lblKetLaporanCus = new javax.swing.JLabel();
        lblLaporanCus = new javax.swing.JLabel();
        lblLogoLaporanCus = new javax.swing.JLabel();
        lblLogoLaporanBulan = new javax.swing.JLabel();
        lblLaporanBulan = new javax.swing.JLabel();
        lblKetLaporanBulan = new javax.swing.JLabel();
        lblKetLaporanBulan1 = new javax.swing.JLabel();
        btnLaporanPerbulan = new javax.swing.JButton();
        lblLogoLaporanTahun = new javax.swing.JLabel();
        lblLaporanTahun = new javax.swing.JLabel();
        lblKetLaporanTahun = new javax.swing.JLabel();
        lblKetLaporanTahun1 = new javax.swing.JLabel();
        btnLaporanPertahun = new javax.swing.JButton();
        pnlLaporancus = new javax.swing.JPanel();
        lblLogoLaporanPembayaranRihlah2 = new javax.swing.JLabel();
        lblLaporanRihlah3 = new javax.swing.JLabel();
        lblKetLaporanRihlah5 = new javax.swing.JLabel();
        lblKetLaporanRihlah6 = new javax.swing.JLabel();
        btnLaporanBarang = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlLaporanBul = new javax.swing.JPanel();
        lblLogoLaporanPembayaranRihlah3 = new javax.swing.JLabel();
        lblLaporanRihlah4 = new javax.swing.JLabel();
        lblKetLaporanRihlah7 = new javax.swing.JLabel();
        lblKetLaporanRihlah8 = new javax.swing.JLabel();
        btnLaporanBulanan = new javax.swing.JButton();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnlMenuInfoAkun = new javax.swing.JPanel();
        pnlHeaderInfoAkun = new javax.swing.JPanel();
        lblHdrHalAkun = new javax.swing.JLabel();
        lblHeadInfoAkun = new javax.swing.JLabel();
        lblUsernameInfo = new javax.swing.JLabel();
        txtInfoUsername = new javax.swing.JTextField();
        lblPasswordInfo = new javax.swing.JLabel();
        txtInfoPassword = new javax.swing.JPasswordField();
        btnChangePass = new javax.swing.JButton();
        ShowPass = new javax.swing.JCheckBox();
        pnData = new javax.swing.JPanel();
        pnlHeaderPembayaran1 = new javax.swing.JPanel();
        lblHdrHalPemb1 = new javax.swing.JLabel();
        lblBarang = new javax.swing.JLabel();
        lblLogoBarang = new javax.swing.JLabel();
        lblKetBarang = new javax.swing.JLabel();
        lblKetBarang1 = new javax.swing.JLabel();
        btnMenageBarang = new javax.swing.JButton();
        lblLogoJasa = new javax.swing.JLabel();
        lblJasa = new javax.swing.JLabel();
        lblKetJasa = new javax.swing.JLabel();
        lblKetJasa1 = new javax.swing.JLabel();
        btnMenageJasa = new javax.swing.JButton();
        btnManagePegawai = new javax.swing.JButton();
        lblKetPeg1 = new javax.swing.JLabel();
        lblKetPeg = new javax.swing.JLabel();
        lblPeg = new javax.swing.JLabel();
        lblLogoPegawai = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblFooterAlamat = new javax.swing.JLabel();
        lblFooterThn = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblTransaksi = new javax.swing.JLabel();
        lblLaporan = new javax.swing.JLabel();
        lblInfoAkun = new javax.swing.JLabel();
        lblHoverAkun = new javax.swing.JLabel();
        lblHoverTransaksi = new javax.swing.JLabel();
        lblHoverData = new javax.swing.JLabel();
        lblHoverLaporan = new javax.swing.JLabel();
        pnlTransaksi = new javax.swing.JPanel();
        pnlHeaderPembayaran2 = new javax.swing.JPanel();
        lblHdrHalPemb2 = new javax.swing.JLabel();
        lblLogoTrans = new javax.swing.JLabel();
        lblTrans = new javax.swing.JLabel();
        lblKetTrans = new javax.swing.JLabel();
        lblKetTrans1 = new javax.swing.JLabel();
        btnPenjualan = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mnItmOpenDN = new javax.swing.JMenuItem();
        mnItemKeluar = new javax.swing.JMenuItem();
        mnData = new javax.swing.JMenu();
        mnItmBarang = new javax.swing.JMenuItem();
        mnItmJasa = new javax.swing.JMenuItem();
        mnItmPeg = new javax.swing.JMenuItem();
        mnTransaksi = new javax.swing.JMenu();
        itmPenjualan = new javax.swing.JMenuItem();
        mnBantuan = new javax.swing.JMenu();
        mnItemAbout = new javax.swing.JMenuItem();
        mnItemHelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 700));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackground.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlBackground.setAlignmentX(1.0F);
        pnlBackground.setAlignmentY(1.0F);
        pnlBackground.setMinimumSize(new java.awt.Dimension(1366, 768));
        pnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlHeader.setAlignmentX(1.0F);
        pnlHeader.setAlignmentY(1.0F);
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("4F-APP ");
        pnlHeader.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel5.setText("Sistem Transaksi Bengkel");
        pnlHeader.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 150, -1));

        jButton10.setBackground(new java.awt.Color(0, 204, 255));
        jButton10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Log Out>>");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        pnlHeader.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 20, -1, -1));

        pnlBackground.add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 60));

        pnlList.setBackground(new java.awt.Color(0, 102, 255));
        pnlList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlBackground.add(pnlList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1370, 4));

        pnlMenuLaporan.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenuLaporan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeaderLaporan.setBackground(new java.awt.Color(0, 204, 255));
        pnlHeaderLaporan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHdrHalLaporan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHdrHalLaporan.setText("Halaman Laporan");
        pnlHeaderLaporan.add(lblHdrHalLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 2, 170, 30));

        pnlMenuLaporan.add(pnlHeaderLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 1120, 40));

        pnlLaporan.setBackground(new java.awt.Color(255, 255, 255));
        pnlLaporan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLaporanCus.setBackground(new java.awt.Color(51, 102, 255));
        btnLaporanCus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLaporanCus.setForeground(new java.awt.Color(255, 255, 255));
        btnLaporanCus.setText("LIHAT");
        btnLaporanCus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLaporanCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanCusActionPerformed(evt);
            }
        });
        pnlLaporan.add(btnLaporanCus, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 220, 110, 40));

        lblKetLaporanCus1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblKetLaporanCus1.setForeground(new java.awt.Color(51, 51, 51));
        lblKetLaporanCus1.setText("Penjualan");
        pnlLaporan.add(lblKetLaporanCus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 190, -1, 20));

        lblKetLaporanCus.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblKetLaporanCus.setForeground(new java.awt.Color(51, 51, 51));
        lblKetLaporanCus.setText("Pilih Menu Ini Untuk Melihat Laporan");
        pnlLaporan.add(lblKetLaporanCus, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, 170, 10));

        lblLaporanCus.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblLaporanCus.setForeground(new java.awt.Color(51, 102, 255));
        lblLaporanCus.setText("Laporan Fiture");
        pnlLaporan.add(lblLaporanCus, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 150, 110, 20));

        lblLogoLaporanCus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LogoLaporanFitur.png"))); // NOI18N
        pnlLaporan.add(lblLogoLaporanCus, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 70, 60, 70));

        lblLogoLaporanBulan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LogoLaporanBulanan.png"))); // NOI18N
        pnlLaporan.add(lblLogoLaporanBulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 70, 70));

        lblLaporanBulan.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblLaporanBulan.setForeground(new java.awt.Color(51, 102, 255));
        lblLaporanBulan.setText("Laporan Penjualan Perbulan");
        pnlLaporan.add(lblLaporanBulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        lblKetLaporanBulan.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblKetLaporanBulan.setForeground(new java.awt.Color(51, 51, 51));
        lblKetLaporanBulan.setText("Pilih Menu Ini Untuk Melihat Laporan");
        pnlLaporan.add(lblKetLaporanBulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 170, -1));

        lblKetLaporanBulan1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblKetLaporanBulan1.setForeground(new java.awt.Color(51, 51, 51));
        lblKetLaporanBulan1.setText("Penjualan Dalam Satu Bulan");
        pnlLaporan.add(lblKetLaporanBulan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, 20));

        btnLaporanPerbulan.setBackground(new java.awt.Color(51, 102, 255));
        btnLaporanPerbulan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLaporanPerbulan.setForeground(new java.awt.Color(255, 255, 255));
        btnLaporanPerbulan.setText("LIHAT");
        btnLaporanPerbulan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLaporanPerbulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanPerbulanActionPerformed(evt);
            }
        });
        pnlLaporan.add(btnLaporanPerbulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 120, 40));

        lblLogoLaporanTahun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LogoLaporanTahunan.png"))); // NOI18N
        pnlLaporan.add(lblLogoLaporanTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 60, 70));

        lblLaporanTahun.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblLaporanTahun.setForeground(new java.awt.Color(51, 102, 255));
        lblLaporanTahun.setText("Laporan Penjualan Pertahun");
        pnlLaporan.add(lblLaporanTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 220, 20));

        lblKetLaporanTahun.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblKetLaporanTahun.setForeground(new java.awt.Color(51, 51, 51));
        lblKetLaporanTahun.setText("Pilih Menu Ini Untuk Melihat Laporan");
        pnlLaporan.add(lblKetLaporanTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 170, 10));

        lblKetLaporanTahun1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblKetLaporanTahun1.setForeground(new java.awt.Color(51, 51, 51));
        lblKetLaporanTahun1.setText("Penjualan Dalam Satu Tahun");
        pnlLaporan.add(lblKetLaporanTahun1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 140, 20));

        btnLaporanPertahun.setBackground(new java.awt.Color(51, 102, 255));
        btnLaporanPertahun.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLaporanPertahun.setForeground(new java.awt.Color(255, 255, 255));
        btnLaporanPertahun.setText("LIHAT");
        btnLaporanPertahun.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLaporanPertahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanPertahunActionPerformed(evt);
            }
        });
        pnlLaporan.add(btnLaporanPertahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 110, 40));

        pnlMenuLaporan.add(pnlLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1120, 570));

        pnlLaporancus.setBackground(new java.awt.Color(255, 255, 255));
        pnlLaporancus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogoLaporanPembayaranRihlah2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LogoLaporanFiturBarang.png"))); // NOI18N
        pnlLaporancus.add(lblLogoLaporanPembayaranRihlah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 70, 70));

        lblLaporanRihlah3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblLaporanRihlah3.setForeground(new java.awt.Color(51, 102, 255));
        lblLaporanRihlah3.setText("Laporan Penjualan Barang");
        pnlLaporancus.add(lblLaporanRihlah3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 200, 20));

        lblKetLaporanRihlah5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblKetLaporanRihlah5.setForeground(new java.awt.Color(51, 51, 51));
        lblKetLaporanRihlah5.setText("Pilih Menu Ini Untuk Melihat Laporan");
        pnlLaporancus.add(lblKetLaporanRihlah5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 170, 10));

        lblKetLaporanRihlah6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblKetLaporanRihlah6.setForeground(new java.awt.Color(51, 51, 51));
        lblKetLaporanRihlah6.setText("Penjualan Barang");
        pnlLaporancus.add(lblKetLaporanRihlah6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, 20));

        btnLaporanBarang.setBackground(new java.awt.Color(51, 102, 255));
        btnLaporanBarang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLaporanBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnLaporanBarang.setText("LIHAT");
        btnLaporanBarang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLaporanBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanBarangActionPerformed(evt);
            }
        });
        pnlLaporancus.add(btnLaporanBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 110, 40));

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        pnlLaporancus.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 220, 30));

        jDateChooser2.setDateFormatString("yyyy-MM-dd");
        pnlLaporancus.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 220, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Tanggal Akhir");
        pnlLaporancus.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 100, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("Tanggal Awal");
        pnlLaporancus.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 100, 20));

        pnlMenuLaporan.add(pnlLaporancus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1090, 570));

        pnlLaporanBul.setBackground(new java.awt.Color(255, 255, 255));
        pnlLaporanBul.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogoLaporanPembayaranRihlah3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LogoLaporanBulanan.png"))); // NOI18N
        pnlLaporanBul.add(lblLogoLaporanPembayaranRihlah3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 70, 70));

        lblLaporanRihlah4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblLaporanRihlah4.setForeground(new java.awt.Color(51, 102, 255));
        lblLaporanRihlah4.setText("Laporan Penjualan Perbulan");
        pnlLaporanBul.add(lblLaporanRihlah4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 200, 20));

        lblKetLaporanRihlah7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblKetLaporanRihlah7.setForeground(new java.awt.Color(51, 51, 51));
        lblKetLaporanRihlah7.setText("Pilih Menu Ini Untuk Melihat Laporan");
        pnlLaporanBul.add(lblKetLaporanRihlah7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 170, 10));

        lblKetLaporanRihlah8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblKetLaporanRihlah8.setForeground(new java.awt.Color(51, 51, 51));
        lblKetLaporanRihlah8.setText("Penjualan Setiap Bulan");
        pnlLaporanBul.add(lblKetLaporanRihlah8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, 20));

        btnLaporanBulanan.setBackground(new java.awt.Color(51, 102, 255));
        btnLaporanBulanan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLaporanBulanan.setForeground(new java.awt.Color(255, 255, 255));
        btnLaporanBulanan.setText("LIHAT");
        btnLaporanBulanan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLaporanBulanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanBulananActionPerformed(evt);
            }
        });
        pnlLaporanBul.add(btnLaporanBulanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 110, 40));

        jDateChooser3.setDateFormatString("yyyy-MM-dd");
        pnlLaporanBul.add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 220, 30));

        jDateChooser4.setDateFormatString("yyyy-MM-dd");
        pnlLaporanBul.add(jDateChooser4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 220, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("Tanggal Akhir");
        pnlLaporanBul.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 100, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("Tanggal Awal");
        pnlLaporanBul.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 100, 20));

        pnlMenuLaporan.add(pnlLaporanBul, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1090, 570));

        pnlBackground.add(pnlMenuLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 1130, 650));

        pnlMenuInfoAkun.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenuInfoAkun.setMinimumSize(new java.awt.Dimension(1020, 580));
        pnlMenuInfoAkun.setPreferredSize(new java.awt.Dimension(1020, 580));
        pnlMenuInfoAkun.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeaderInfoAkun.setBackground(new java.awt.Color(0, 204, 255));
        pnlHeaderInfoAkun.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHdrHalAkun.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHdrHalAkun.setText("Halaman Informasi Akun");
        pnlHeaderInfoAkun.add(lblHdrHalAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 2, 230, 30));

        pnlMenuInfoAkun.add(pnlHeaderInfoAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 1120, 40));

        lblHeadInfoAkun.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHeadInfoAkun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user.png"))); // NOI18N
        lblHeadInfoAkun.setText("  Informasi Akun");
        pnlMenuInfoAkun.add(lblHeadInfoAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 230, -1));

        lblUsernameInfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUsernameInfo.setText("Username");
        pnlMenuInfoAkun.add(lblUsernameInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        txtInfoUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtInfoUsername.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        pnlMenuInfoAkun.add(txtInfoUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 210, 30));

        lblPasswordInfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPasswordInfo.setText("Password");
        pnlMenuInfoAkun.add(lblPasswordInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        txtInfoPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlMenuInfoAkun.add(txtInfoPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 210, 30));

        btnChangePass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnChangePass.setText("Update");
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });
        pnlMenuInfoAkun.add(btnChangePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 210, 30));

        ShowPass.setBackground(new java.awt.Color(255, 255, 255));
        ShowPass.setText("Tampilkan Password");
        ShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPassActionPerformed(evt);
            }
        });
        pnlMenuInfoAkun.add(ShowPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        pnlBackground.add(pnlMenuInfoAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 1140, 600));

        pnData.setBackground(new java.awt.Color(255, 255, 255));
        pnData.setMinimumSize(new java.awt.Dimension(1020, 580));
        pnData.setPreferredSize(new java.awt.Dimension(1020, 580));
        pnData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeaderPembayaran1.setBackground(new java.awt.Color(0, 204, 255));
        pnlHeaderPembayaran1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHdrHalPemb1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHdrHalPemb1.setText("Halaman Manage Data");
        pnlHeaderPembayaran1.add(lblHdrHalPemb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 2, 200, 30));

        pnData.add(pnlHeaderPembayaran1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 1120, 40));

        lblBarang.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblBarang.setForeground(new java.awt.Color(51, 102, 255));
        lblBarang.setText("Data Barang");
        pnData.add(lblBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 100, -1));

        lblLogoBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/barang.png"))); // NOI18N
        pnData.add(lblLogoBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 70, 70));

        lblKetBarang.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblKetBarang.setForeground(new java.awt.Color(51, 51, 51));
        lblKetBarang.setText("Pilih Menu Ini Untuk Memanage");
        pnData.add(lblKetBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        lblKetBarang1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblKetBarang1.setForeground(new java.awt.Color(51, 51, 51));
        lblKetBarang1.setText("Data Barang");
        pnData.add(lblKetBarang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, 20));

        btnMenageBarang.setBackground(new java.awt.Color(51, 102, 255));
        btnMenageBarang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMenageBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnMenageBarang.setText("Manage");
        btnMenageBarang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnMenageBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenageBarangActionPerformed(evt);
            }
        });
        pnData.add(btnMenageBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 110, 40));

        lblLogoJasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/jasa.png"))); // NOI18N
        pnData.add(lblLogoJasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 70, 70));

        lblJasa.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblJasa.setForeground(new java.awt.Color(51, 102, 255));
        lblJasa.setText("Data Jasa");
        pnData.add(lblJasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, 80, -1));

        lblKetJasa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblKetJasa.setForeground(new java.awt.Color(51, 51, 51));
        lblKetJasa.setText("Pilih Menu Ini Untuk Memanage");
        pnData.add(lblKetJasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, -1, -1));

        lblKetJasa1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblKetJasa1.setForeground(new java.awt.Color(51, 51, 51));
        lblKetJasa1.setText("Data Jasa");
        pnData.add(lblKetJasa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, -1, 20));

        btnMenageJasa.setBackground(new java.awt.Color(51, 102, 255));
        btnMenageJasa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMenageJasa.setForeground(new java.awt.Color(255, 255, 255));
        btnMenageJasa.setText("Manage");
        btnMenageJasa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnMenageJasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenageJasaActionPerformed(evt);
            }
        });
        pnData.add(btnMenageJasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 110, 40));

        btnManagePegawai.setBackground(new java.awt.Color(51, 102, 255));
        btnManagePegawai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnManagePegawai.setForeground(new java.awt.Color(255, 255, 255));
        btnManagePegawai.setText("Manage");
        btnManagePegawai.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnManagePegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePegawaiActionPerformed(evt);
            }
        });
        pnData.add(btnManagePegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 110, 40));

        lblKetPeg1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblKetPeg1.setForeground(new java.awt.Color(51, 51, 51));
        lblKetPeg1.setText("Data Pegawai");
        pnData.add(lblKetPeg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, 20));

        lblKetPeg.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblKetPeg.setForeground(new java.awt.Color(51, 51, 51));
        lblKetPeg.setText("Pilih Menu Ini Untuk Memanage");
        pnData.add(lblKetPeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, -1));

        lblPeg.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblPeg.setForeground(new java.awt.Color(51, 102, 255));
        lblPeg.setText("Data Pegawai");
        pnData.add(lblPeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 110, -1));

        lblLogoPegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pegawai.png"))); // NOI18N
        pnData.add(lblLogoPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 70, 70));

        pnlBackground.add(pnData, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 1140, 680));

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/4F.PNG"))); // NOI18N
        pnlMenu.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        lblFooterAlamat.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblFooterAlamat.setText("Jl Raya Sutorejo No 26 - +6281615590264");
        pnlMenu.add(lblFooterAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        lblFooterThn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblFooterThn.setText("SURABAYA - JAWA TIMUR");
        pnlMenu.add(lblFooterThn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, -1, -1));

        lblWelcome.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(51, 204, 255));
        lblWelcome.setText("MENU");
        pnlMenu.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 40));

        lblData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/data.png"))); // NOI18N
        lblData.setText("    Manage Data");
        lblData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDataMouseClicked(evt);
            }
        });
        pnlMenu.add(lblData, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 170, 30));

        lblTransaksi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/MenuPembayaran.png"))); // NOI18N
        lblTransaksi.setText("    Transaksi");
        lblTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTransaksiMouseClicked(evt);
            }
        });
        pnlMenu.add(lblTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 170, 30));

        lblLaporan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/MenuLaporan.png"))); // NOI18N
        lblLaporan.setText("    Laporan");
        lblLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLaporanMouseClicked(evt);
            }
        });
        pnlMenu.add(lblLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 170, 30));

        lblInfoAkun.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInfoAkun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/MenuAccount.png"))); // NOI18N
        lblInfoAkun.setText("    Informasi Akun");
        lblInfoAkun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInfoAkun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInfoAkunMouseClicked(evt);
            }
        });
        pnlMenu.add(lblInfoAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 259, 170, 30));

        lblHoverAkun.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        pnlMenu.add(lblHoverAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 230, 50));

        lblHoverTransaksi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        pnlMenu.add(lblHoverTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 230, 50));

        lblHoverData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        pnlMenu.add(lblHoverData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 230, 50));

        lblHoverLaporan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        pnlMenu.add(lblHoverLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 230, 50));

        pnlBackground.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 230, 680));

        pnlTransaksi.setBackground(new java.awt.Color(255, 255, 255));
        pnlTransaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeaderPembayaran2.setBackground(new java.awt.Color(0, 204, 255));
        pnlHeaderPembayaran2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHdrHalPemb2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHdrHalPemb2.setText("Halaman Transaksi");
        pnlHeaderPembayaran2.add(lblHdrHalPemb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 2, 200, 30));

        pnlTransaksi.add(pnlHeaderPembayaran2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 1120, 40));

        lblLogoTrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/transaksi.png"))); // NOI18N
        pnlTransaksi.add(lblLogoTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 70, 70));

        lblTrans.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTrans.setForeground(new java.awt.Color(51, 102, 255));
        lblTrans.setText("Transaksi Penjualan");
        pnlTransaksi.add(lblTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 160, -1));

        lblKetTrans.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblKetTrans.setForeground(new java.awt.Color(51, 51, 51));
        lblKetTrans.setText("Pilih Menu Ini Untuk Melakukan");
        pnlTransaksi.add(lblKetTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, -1, -1));

        lblKetTrans1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblKetTrans1.setForeground(new java.awt.Color(51, 51, 51));
        lblKetTrans1.setText("Transaksi Penjualan");
        pnlTransaksi.add(lblKetTrans1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, 20));

        btnPenjualan.setBackground(new java.awt.Color(51, 102, 255));
        btnPenjualan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPenjualan.setForeground(new java.awt.Color(255, 255, 255));
        btnPenjualan.setText("Masuk");
        btnPenjualan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenjualanActionPerformed(evt);
            }
        });
        pnlTransaksi.add(btnPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 110, 40));

        pnlBackground.add(pnlTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 1140, 640));

        getContentPane().add(pnlBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 740));

        MenuBar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        mnFile.setText("File");

        mnItmOpenDN.setText("Open DB-XAMPP");
        mnItmOpenDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItmOpenDNActionPerformed(evt);
            }
        });
        mnFile.add(mnItmOpenDN);

        mnItemKeluar.setText("Log Out");
        mnItemKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemKeluarActionPerformed(evt);
            }
        });
        mnFile.add(mnItemKeluar);

        MenuBar.add(mnFile);

        mnData.setText("Data");

        mnItmBarang.setText("Data Barang");
        mnItmBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItmBarangActionPerformed(evt);
            }
        });
        mnData.add(mnItmBarang);

        mnItmJasa.setText("Data Jasa");
        mnItmJasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItmJasaActionPerformed(evt);
            }
        });
        mnData.add(mnItmJasa);

        mnItmPeg.setText("Data Pegawai");
        mnItmPeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItmPegActionPerformed(evt);
            }
        });
        mnData.add(mnItmPeg);

        MenuBar.add(mnData);

        mnTransaksi.setText("Transaksi");

        itmPenjualan.setText("Penjualan");
        itmPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmPenjualanActionPerformed(evt);
            }
        });
        mnTransaksi.add(itmPenjualan);

        MenuBar.add(mnTransaksi);

        mnBantuan.setText("Bantuan");

        mnItemAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Bantuan.png"))); // NOI18N
        mnItemAbout.setText("Tentang");
        mnItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemAboutActionPerformed(evt);
            }
        });
        mnBantuan.add(mnItemAbout);

        mnItemHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Help.png"))); // NOI18N
        mnItemHelp.setText("Bantuan");
        mnItemHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemHelpActionPerformed(evt);
            }
        });
        mnBantuan.add(mnItemHelp);

        MenuBar.add(mnBantuan);

        setJMenuBar(MenuBar);

        setSize(new java.awt.Dimension(1382, 769));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void lblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDataMouseClicked
        // TODO add your handling code here:
        lblHoverTransaksi.setVisible(false);
        lblHoverData.setVisible(true);
        lblHoverLaporan.setVisible(false);
        lblHoverAkun.setVisible(false);

        pnData.setVisible(true);
        pnlTransaksi.setVisible(false);
        pnlMenuLaporan.setVisible(false);
        pnlMenuInfoAkun.setVisible(false);
    }//GEN-LAST:event_lblDataMouseClicked

    private void lblTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTransaksiMouseClicked
        // TODO add your handling code here:
        lblHoverTransaksi.setVisible(true);
        lblHoverData.setVisible(false);
        lblHoverLaporan.setVisible(false);
        lblHoverAkun.setVisible(false);

        pnData.setVisible(false);
        pnlTransaksi.setVisible(true);
        pnlMenuLaporan.setVisible(false);
        pnlMenuInfoAkun.setVisible(false);
    }//GEN-LAST:event_lblTransaksiMouseClicked

    private void lblLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLaporanMouseClicked
        // TODO add your handling code here:
        lblHoverTransaksi.setVisible(false);
        lblHoverData.setVisible(false);
        lblHoverLaporan.setVisible(true);
        lblHoverAkun.setVisible(false);

        pnData.setVisible(false);
        pnlTransaksi.setVisible(false);
        pnlMenuLaporan.setVisible(true);
        pnlLaporan.setVisible(true);
        pnlLaporancus.setVisible(false);
        pnlLaporanBul.setVisible(false);
        pnlMenuInfoAkun.setVisible(false);
    }//GEN-LAST:event_lblLaporanMouseClicked

    private void lblInfoAkunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInfoAkunMouseClicked
        // TODO add your handling code here:
        lblHoverTransaksi.setVisible(false);
        lblHoverData.setVisible(false);
        lblHoverLaporan.setVisible(false);
        lblHoverAkun.setVisible(true);

        pnData.setVisible(false);
        pnlTransaksi.setVisible(false);
        pnlMenuLaporan.setVisible(false);
        pnlMenuInfoAkun.setVisible(true);
    }//GEN-LAST:event_lblInfoAkunMouseClicked

    private void mnItemKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemKeluarActionPerformed
        // TODO add your handling code here:
        new FormLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_mnItemKeluarActionPerformed

    private void mnItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemAboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "4F APP Adalah Aplikasi Sistem Informasi Transaksi 4F Motor"
                + "\nDibuat oleh Mahasiswa Kerja Praktek Teknik Informatika ITATS Surabaya dengan tujuan untuk"
                + "\nmembantu dan memudahkan 4F Motor dalam kegiatan Transaksi Dan Laporan."
                + "\n\nApplication Version 1.0.0", "Tentang 4F APP", 1);
    }//GEN-LAST:event_mnItemAboutActionPerformed

    private void mnItemHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemHelpActionPerformed
        // TODO add your handling code here:
        new Bantuan().setVisible(true);
        dispose();
    }//GEN-LAST:event_mnItemHelpActionPerformed

    private void btnLaporanPerbulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanPerbulanActionPerformed
        // TODO add your handling code here:
        pnlLaporan.setVisible(false);
        pnlLaporanBul.setVisible(true);
    }//GEN-LAST:event_btnLaporanPerbulanActionPerformed

    private void mnItmJasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItmJasaActionPerformed
        // TODO add your handling code here:
        new FormJasa(id_pegawai).setVisible(true);
        dispose();
    }//GEN-LAST:event_mnItmJasaActionPerformed

    private void mnItmBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItmBarangActionPerformed
        // TODO add your handling code here:
        new FormBarang(id_pegawai).setVisible(true);
        dispose();
    }//GEN-LAST:event_mnItmBarangActionPerformed

    private void btnLaporanPertahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanPertahunActionPerformed
        // TODO add your handling code here:
        db.Connect();
        String tahun = JOptionPane.showInputDialog(null, "Masukkan Tahun \n Contoh : 2019");
        if((tahun != null)){
            String NamaFile = "/Laporan/LaporanPerTahun.jasper";
            HashMap hash = new HashMap();
            try {
               hash.put("ptahun", tahun);
                CetakLaporan(NamaFile,hash);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnLaporanPertahunActionPerformed

    private void btnMenageBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenageBarangActionPerformed
        // TODO add your handling code here:
        new FormBarang(id_pegawai).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMenageBarangActionPerformed

    private void btnMenageJasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenageJasaActionPerformed
        // TODO add your handling code here:
        new FormJasa(id_pegawai).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMenageJasaActionPerformed

    private void btnManagePegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePegawaiActionPerformed
        // TODO add your handling code here:
        new FormPegawai().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnManagePegawaiActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(this.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void mnItmOpenDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItmOpenDNActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().open(new File("C:\\xampp\\xampp-control.exe"));
        } catch (IOException ex) {
            Logger.getLogger(FormLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnItmOpenDNActionPerformed

    private void btnPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenjualanActionPerformed
        // TODO add your handling code here:
        new FormPenjualan(id_pegawai).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPenjualanActionPerformed

    private void itmPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmPenjualanActionPerformed
        // TODO add your handling code here:
        new FormPenjualan(id_pegawai).setVisible(true);
        dispose();
    }//GEN-LAST:event_itmPenjualanActionPerformed

    private void mnItmPegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItmPegActionPerformed
        // TODO add your handling code here:
        new FormPegawai().setVisible(true);
        dispose();
    }//GEN-LAST:event_mnItmPegActionPerformed

    private void btnLaporanCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanCusActionPerformed
        // TODO add your handling code here:
        pnlLaporan.setVisible(false);
        pnlLaporancus.setVisible(true);
    }//GEN-LAST:event_btnLaporanCusActionPerformed

    private void btnLaporanBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanBarangActionPerformed
        // TODO add your handling code here:
        db.Connect();
        String tgl1 = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
        String tgl2 = ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText();
        if((tgl1 != null)&&(tgl2 != null)){
            String NamaFile = "/Laporan/LaporanPenjualanBarang.jasper";
            HashMap hash = new HashMap();
            try {
                hash.put("tglAwal", tgl1);
                hash.put("tglAkhir", tgl2);
                CetakLaporan(NamaFile,hash);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnLaporanBarangActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        new FormLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void ShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPassActionPerformed
        // TODO add your handling code here:
        if (ShowPass.isSelected()) {
            txtInfoPassword.setEchoChar((char) 0);

        } else {
            txtInfoPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_ShowPassActionPerformed

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        // TODO add your handling code here:
            GantiPass();
            cekuser();
    }//GEN-LAST:event_btnChangePassActionPerformed

    private void btnLaporanBulananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanBulananActionPerformed
        // TODO add your handling code here:
        String tgl1 = ((JTextField)jDateChooser3.getDateEditor().getUiComponent()).getText();
        String tgl2 = ((JTextField)jDateChooser4.getDateEditor().getUiComponent()).getText();
        if((tgl1 != null)&&(tgl2 != null)){
            String NamaFile = "/Laporan/LaporanPerBulan.jasper";
            HashMap hash = new HashMap();
            try {
                hash.put("tAwal", tgl1);
                hash.put("tAkhir", tgl2);
                CetakLaporan(NamaFile,hash);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnLaporanBulananActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JCheckBox ShowPass;
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnLaporanBarang;
    private javax.swing.JButton btnLaporanBulanan;
    private javax.swing.JButton btnLaporanCus;
    private javax.swing.JButton btnLaporanPerbulan;
    private javax.swing.JButton btnLaporanPertahun;
    private javax.swing.JButton btnManagePegawai;
    private javax.swing.JButton btnMenageBarang;
    private javax.swing.JButton btnMenageJasa;
    private javax.swing.JButton btnPenjualan;
    private javax.swing.JMenuItem itmPenjualan;
    private javax.swing.JButton jButton10;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblBarang;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblFooterAlamat;
    private javax.swing.JLabel lblFooterThn;
    private javax.swing.JLabel lblHdrHalAkun;
    private javax.swing.JLabel lblHdrHalLaporan;
    private javax.swing.JLabel lblHdrHalPemb1;
    private javax.swing.JLabel lblHdrHalPemb2;
    private javax.swing.JLabel lblHeadInfoAkun;
    protected javax.swing.JLabel lblHoverAkun;
    protected javax.swing.JLabel lblHoverData;
    protected javax.swing.JLabel lblHoverLaporan;
    protected javax.swing.JLabel lblHoverTransaksi;
    private javax.swing.JLabel lblInfoAkun;
    private javax.swing.JLabel lblJasa;
    private javax.swing.JLabel lblKetBarang;
    private javax.swing.JLabel lblKetBarang1;
    private javax.swing.JLabel lblKetJasa;
    private javax.swing.JLabel lblKetJasa1;
    private javax.swing.JLabel lblKetLaporanBulan;
    private javax.swing.JLabel lblKetLaporanBulan1;
    private javax.swing.JLabel lblKetLaporanCus;
    private javax.swing.JLabel lblKetLaporanCus1;
    private javax.swing.JLabel lblKetLaporanRihlah5;
    private javax.swing.JLabel lblKetLaporanRihlah6;
    private javax.swing.JLabel lblKetLaporanRihlah7;
    private javax.swing.JLabel lblKetLaporanRihlah8;
    private javax.swing.JLabel lblKetLaporanTahun;
    private javax.swing.JLabel lblKetLaporanTahun1;
    private javax.swing.JLabel lblKetPeg;
    private javax.swing.JLabel lblKetPeg1;
    private javax.swing.JLabel lblKetTrans;
    private javax.swing.JLabel lblKetTrans1;
    private javax.swing.JLabel lblLaporan;
    private javax.swing.JLabel lblLaporanBulan;
    private javax.swing.JLabel lblLaporanCus;
    private javax.swing.JLabel lblLaporanRihlah3;
    private javax.swing.JLabel lblLaporanRihlah4;
    private javax.swing.JLabel lblLaporanTahun;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogoBarang;
    private javax.swing.JLabel lblLogoJasa;
    private javax.swing.JLabel lblLogoLaporanBulan;
    private javax.swing.JLabel lblLogoLaporanCus;
    private javax.swing.JLabel lblLogoLaporanPembayaranRihlah2;
    private javax.swing.JLabel lblLogoLaporanPembayaranRihlah3;
    private javax.swing.JLabel lblLogoLaporanTahun;
    private javax.swing.JLabel lblLogoPegawai;
    private javax.swing.JLabel lblLogoTrans;
    private javax.swing.JLabel lblPasswordInfo;
    private javax.swing.JLabel lblPeg;
    private javax.swing.JLabel lblTrans;
    private javax.swing.JLabel lblTransaksi;
    private javax.swing.JLabel lblUsernameInfo;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JMenu mnBantuan;
    private javax.swing.JMenu mnData;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenuItem mnItemAbout;
    private javax.swing.JMenuItem mnItemHelp;
    private javax.swing.JMenuItem mnItemKeluar;
    private javax.swing.JMenuItem mnItmBarang;
    private javax.swing.JMenuItem mnItmJasa;
    private javax.swing.JMenuItem mnItmOpenDN;
    private javax.swing.JMenuItem mnItmPeg;
    private javax.swing.JMenu mnTransaksi;
    protected javax.swing.JPanel pnData;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlHeaderInfoAkun;
    private javax.swing.JPanel pnlHeaderLaporan;
    private javax.swing.JPanel pnlHeaderPembayaran1;
    private javax.swing.JPanel pnlHeaderPembayaran2;
    private javax.swing.JPanel pnlLaporan;
    private javax.swing.JPanel pnlLaporanBul;
    private javax.swing.JPanel pnlLaporancus;
    private javax.swing.JPanel pnlList;
    protected javax.swing.JPanel pnlMenu;
    protected javax.swing.JPanel pnlMenuInfoAkun;
    protected javax.swing.JPanel pnlMenuLaporan;
    protected javax.swing.JPanel pnlTransaksi;
    private javax.swing.JPasswordField txtInfoPassword;
    public static javax.swing.JTextField txtInfoUsername;
    // End of variables declaration//GEN-END:variables

    private void setuser(){
        db.Connect();
        try{
            String sql = "SELECT * FROM pegawai WHERE id_pegawai = '"+id_pegawai+"'";
            st = db.getConnection().createStatement();
            rs = st.executeQuery(sql);
            if(rs.next()){
                txtInfoUsername.setText(rs.getString("username"));
                txtInfoPassword.setText(rs.getString("password"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void setuserpemilik(){
        db.Connect();
        try{
            String sql = "SELECT * FROM pemilik WHERE id_pemilik = '"+id_pegawai+"'";
            st = db.getConnection().createStatement();
            rs = st.executeQuery(sql);
            if(rs.next()){
                txtInfoUsername.setText(rs.getString("username"));
                txtInfoPassword.setText(rs.getString("password"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void cekuser(){
        if(id_pegawai.equals("PM01")){
            lblTransaksi.setVisible(false);
            pnlTransaksi.setVisible(false);
            lblLogoBarang.setVisible(false);
            lblBarang.setVisible(false);
            lblKetBarang.setVisible(false);
            lblKetBarang1.setVisible(false);
            btnMenageBarang.setVisible(false);
            lblLogoJasa.setVisible(false);
            lblJasa.setVisible(false);
            lblKetJasa.setVisible(false);
            lblKetJasa1.setVisible(false);
            btnMenageJasa.setVisible(false);
            btnPenjualan.setEnabled(false);
            mnTransaksi.setVisible(false);
            mnItmBarang.setVisible(false);
            mnItmJasa.setVisible(false);
            setuserpemilik();
        }else{
            pnlMenuLaporan.setVisible(false);
            lblLaporan.setVisible(false);
            lblLogoPegawai.setVisible(false);
            lblPeg.setVisible(false);
            lblKetPeg.setVisible(false);
            lblKetPeg1.setVisible(false);
            btnManagePegawai.setVisible(false);
            mnItmPeg.setVisible(false);
            setuser();
        }
    }
    private void CetakLaporan(String sourcefilename, HashMap hash){
        cn = db.getConnection();
        try {
            InputStream report;
            report = getClass().getResourceAsStream(sourcefilename);
            JasperPrint jprint = JasperFillManager.fillReport(report,hash, cn);
            JasperViewer viewer = new JasperViewer(jprint, false);
            viewer.setFitPageZoomRatio();
            viewer.setVisible(true);
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
    }
    private void GantiPass(){
        if(id_pegawai.equals("PM01")){
            db.Connect();
            try{
                String sql = "update pemilik set username = '"+txtInfoUsername.getText()
                        +"',password = '"+txtInfoPassword.getText()
                        +"' WHERE id_pemilik = '"+id_pegawai+"'";
                st = db.getConnection().createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Ganti Password Berhasil");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Gagal Mengubah Password !");
            }
        }else{
            db.Connect();
            try{
                String sql = "update pegawai set username = '"+txtInfoUsername.getText()
                        +"',password = '"+txtInfoPassword.getText()
                        +"' WHERE id_pegawai = '"+id_pegawai+"'";
                st = db.getConnection().createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Ganti Password Berhasil");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Gagal Mengubah Password !");
            }
        }
    }
}
